name: Test
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        name: [go-ipfs, fs-repo-migrations, gx, gx-go, ipfs-cluster-ctl, ipfs-cluster-follow, ipfs-cluster-service, ipfs-ds-convert, ipfs-update, ipget, libp2p-relay-daemon]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          path: download-ipfs-distribution-action
      - id: distribution
        uses: ./download-ipfs-distribution-action
        with:
          name: ${{ matrix.name }}
          cache: false
      # ipget for linux-amd64 requires GLIBC_2.32 but GLIBC_2.31 is installed
      - if: ${{ matrix.os != 'ubuntu-latest' || matrix.name != 'ipget' }}
        run: ${{ steps.distribution.outputs.executable }} --help
        shell: bash
